### ISSUE TITLE
Infinite redirect loop on proxy providers since 2024.10

### ISSUE THREAD

**Issue by Buco7854** [goauthentik/authentik#11883]
**Describe the bug**
Every proxy providers i have now are blocked in an infinite loop. Even new one i create are affected.

**To Reproduce**
Go to an application that use a proxy provider

**Expected behavior**
The authorization process should be passed and the website displayed

**Logs**
 REDACTED

**Version and Deployment(please complete the following information):**

    authentik version: 2024.10.0
    Deployment: docker-compose

**Additional context**
Anything else works fine.
chnaging docker image version back to 2024.8 doesnt work tho seems like the scheme are incompatible.
Was forced to restore a backup to go back to 2024.8

**Comment by devzwf** [comment]
i have the same issue.
also worker as well is on infinite loop

**Comment by dmfrey** [comment]
+1 to this issue

**Comment by MineTech13** [comment]
+1 here too

**Comment by vish9812** [comment]
I'm getting the following error in this infinite loop:

```
psycopg.errors.DuplicateColumn: column "invalidation_flow_id" of relation "authentik_core_provider" already exists
```

**Comment by miccico** [comment]
+1

**Comment by TiiFuchs** [comment]
+1

**Comment by MichaelSp** [comment]
I also have ` column "invalidation_flow_id" of relation "authentik_core_provider" already exists` in my k8s helm based deployment

**Comment by HumnResources** [comment]
Confirm same issue. Interestingly, when I initially setup 2024.10 my proxies were working fine. But by the time I finished getting all my config setup (branding/flows/etc) they were looping and unrecoverable.

**Comment by gergosimonyi** [comment]
Based on the error in the logs, this should be fixed by #11879

Aside: the `INSERT INTO` statements in your pasted logs contain a JWT which contains credentials. They are now leaked, you should rotate all of them. We can't really filter `docker-compose` output so if you post any logs as part of a ticket in the future, please look through them and remove sensitive data by hand.

**Comment by Buco7854** [comment]
> Based on the error in the logs, this should be fixed by #11879
> 
> Aside: the `INSERT INTO` statements in your pasted logs contain a JWT which contains credentials. They are now leaked, you should rotate all of them. We can't really filter `docker-compose` output so if you post any logs as part of a ticket in the future, please look through them and remove sensitive data by hand.

Thank you, I'll try when a new image will be available. How do i actually rotate the JWTs. Are those specific to a user or the Authentik App itself?

**Comment by gergosimonyi** [comment]
Oh, I didn't mean rotate the JWT. Rotate the credentials encoded in the JWT. You can see what was exposed if you plug the JWT into a service like https://jwt.io/#debugger-io

**Comment by Buco7854** [comment]
> Oh, I didn't mean rotate the JWT. Rotate the credentials encoded in the JWT. You can see what was exposed if you plug the JWT into a service like https://jwt.io/#debugger-io

Well I deleted the logs. The jwt contained the application URL and some temporary tokens I guess so it's fine but while looking at the logs I realised my email wasnt properly replaced everywhere😅. Thanks.

**Comment by BeryJu** [comment]
@Buco7854 FYI the edit history of your issue is still public so the logs are still visible, and so are the credentials. We recommend you rotate the passwords in calibre and another application that is not named. We can also delete the issue.

**Comment by bhavikbhakta** [comment]
Same issue here. Both with Local & Social Identity logins on NGINX Proxy Manager.

**Comment by bryceprutsos** [comment]
I just updated the 2024.10.1 and the problem is still there so 🤷

**Comment by MrBE4R** [comment]
Hi,

The image for 2024.10.1 (sha256:b6b2fc02ea1c77943b8aa519af7f392bc1fcc2fc6341279bf7b54a9bc7fbe4e7) did correct this bug on my deployments.

Cheers.

**Comment by bnctth** [comment]
For me it wouldn't work with an alternative server name (aka the outpost has AUTHENTIK_HOST: http://server:9000 and AUTHENTIK_HOST_BROWSER: https://[public domain]). The only solution was to the public domain as AUTHENTIK_HOST for both the deployment of the outpost and its configuration in authentik

**Comment by dandrade-wave** [comment]
error: "oidc: id token issued by a different provider
  - expected "https://auth.xxx.localhost/application/o/app1/" (AUTHENTIK_HOST_BROWSER)
  - got "http://authentik-server:9000/application/o/app1/" (AUTHENTIK_HOST)

**Comment by mgrove36** [comment]
Hiya, I'm getting this infinite redirect loop as well. The event logs in the admin dashboard show the application being authorised, and then a generic system exception that UUID Objects aren't JSON serialisable:

```
Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/oauth2/views/token.py", line 497, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/oauth2/views/token.py", line 526, in post
    return TokenResponse(self.create_code_response())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/oauth2/views/token.py", line 561, in create_code_response
    access_token.id_token = access_id_token
    ^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/oauth2/models.py", line 438, in id_token
    self.token = value.to_access_token(self.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/oauth2/id_token.py", line 174, in to_access_token
    return provider.encode(final)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/oauth2/models.py", line 310, in encode
    encoded = encode(payload, key, algorithm=alg, headers=headers)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/jwt/api_jwt.py", line 68, in encode
    json_payload = self._encode_payload(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/jwt/api_jwt.py", line 95, in _encode_payload
    return json.dumps(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
builtins.TypeError: Object of type UUID is not JSON serializable
```

**Comment by tomtom5152** [comment]
I'm also seeing the exact same error as @mgrove36 now.

For reference this is image 
```
ghcr.io/goauthentik/server:2024.10.1
ghcr.io/goauthentik/server@sha256:52611cf73ec6880b76a2e437f57ac3f2213b1000f7c82080edc6201b33718803
```

**Comment by martadams89** [comment]
I am also getting the same as @mgrove36

**Comment by mgrove36** [comment]
Looks like this is caused by #11949

**Comment by dmfrey** [comment]
seems to have resolved itself

**Comment by martadams89** [comment]
I just updated to 2024.10.2 and I appeared to still have the same issue, had to downgrade to get working agian.

**Comment by Silvan-M** [comment]
Same problem. Anyone able to resolve the issue, still happens for me on 2024.10.2.

**Comment by mgrove36** [comment]
Same for me. I'm getting the same error as I posted above still. @BeryJu do you have any insights?

**Comment by tomtom5152** [comment]
Also still getting this, with the same error about UUID serialisation

**Comment by Silvan-M** [comment]
Issue just resolved itself for me. Not sure what caused it to work. The only thing I changed was fixing an error I got in the console described [here](https://www.reddit.com/r/unRAID/comments/1ax596x/authentik/) (e.g. I gave read/write permissions for `/media/public`). However not sure if that was the issue, since it didn't resolve the redirection loop until about one day later.

**Comment by martadams89** [comment]
I managed to figure it out. for me... I was using the helm chart and had persistent volumes enabled for /certs /blueprints and /templates.

I also changed my postgres password from file:///authentik-secrets/postgres_password to $__env{AUTHENTIK_POSTGRESQL__PASSWORD} and finally I removed any redis password vars and password auth settings.

Upgraded from 2024.8 to 2024.12 and my proxy forwarding works fine

**Comment by AndersTao** [comment]
I found my problem last night 🫣
Using the default docker-compose file, I only updated the "server" version directly in the docker file, and forgot all about the ATHENTIK_TAG from the .env file, used by the "worker" service 😖

After updating the "worker" version to 2024.12, everything is working again
