### ISSUE TITLE
Reputation policy is not being applied.

### ISSUE THREAD

**Issue by Dental1347** [goauthentik/authentik#12248]
**Describe the bug**
I am currently facing an issue which has been discussed in detail within the discord server. I have been using a policy for a long time, which will -1 the reputation of a certain IP address if they login incorrectly. In turn, when this reaches the threshold of -5, it would cause the user to be unable to login to authentik, as it would simply say they are denied to login.

This used to be the case for a long time, but I am unable to restrict access to it currently. 
![image](https://github.com/user-attachments/assets/5106a28d-8d9d-40a9-86fe-9a1e7849df10)
The above shows how my flow looks, this is the default-authentication-flow. I followed the tutorial a while ago by cooptonian.

The things edited are the authentication which I have set to No Requirement. Within stage bindings everything is as default. default authentication-password is set to 5 failed login attempts. (But as you may be able to guess, this doesn't work).

Under Policy / Group / User Bindings, I have created a policy ip-reputation.
![image](https://github.com/user-attachments/assets/dde27122-4197-4d41-a2f3-724c594953b1)
![image](https://github.com/user-attachments/assets/37664c99-55f4-4f61-9b9c-00663cbbebee)
I have set negate to on/off, don't pass and pass, nothing has been functioning correctly.

**To Reproduce**
--

**Expected behavior**
I expect with this flow to restrict the user on a certain IP trying to login (with incorrect credentials) to brute force my authentik instance, by blocking the login page for a certain amount of time until the reputation score has been reset to 0.

**Screenshots**
See above.

**Logs**
The only logs I found that may be applicable is this line as soon as I enter the page with any user:
```
{"auth_via": "unauthenticated", "domain_url": "{redacted}", "errors": {"captcha_stage": ["This field may not be null."]}, "event": "f(ch): invalid challenge response", "host": "{redacted}", "level": "error", "logger": "authentik.flows.stage", "pid": 43, "request_id": "{redacted}", "schema_name": "public", "stage": "default-authentication-identification", "stage_view": "authentik.stages.identification.stage.IdentificationStageView", "timestamp": "2024-12-02T20:19:28.203960"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: [2024.10.4](https://goauthentik.io/docs/releases/2024.10)
-   Deployment: [e.g. docker-compose, helm] Unraid template. (docker)

**Additional context**
This has worked in ealier versions, I just don't know when it broke as I was unable to check for the past 4 months.

Hope this info is sufficient.

**Comment by Berjou** [comment]
Hi. I'm new to authentik and it is possible that I missed something. But trying to setup a reputation policy like this one, I reached the same conclusion. Trying different combinations of negate result / pass / don't pass, I was not able to make it work. I can see my reputation score decreasing below the threshold during my tests, but authentik never denied me another login attempt. I'm using the 2024.12 version installed with docker compose, did not have the time to try on previous versions yet.

**Comment by BeryJu** [comment]
Especially when checking the IP reputation, I'm assuming you verified that authentik gets the correct Client IP in the reputation tab? There is also some caching of the policies involved here that we're looking into

**Comment by Berjou** [comment]
Yes. I can confirm that the IP in the reputation tab is the public IP of the client I used for testing. And even if it was not the case, because of a reverse proxy misconfiguration or whatever, I assume that regardless of the IP, once it crossed the reputation threshold, the policy should fail.

**Comment by Dental1347** [comment]
> Especially when checking the IP reputation, I'm assuming you verified that authentik gets the correct Client IP in the reputation tab? There is also some caching of the policies involved here that we're looking into

Yes this is the case. Would love to have an update on this if possible. This used to work flawlessly. I have implemented my crowdsec instance to scan on failed logins and handle them, but authentik cannot do this by itself at the moment. At least not with the setup I'm familiar with.

**Comment by derritter88** [comment]
Can confirm that too.
On " Reputation scores" score I can see that the score goes down kind of infinite while my setup restricts -3.

I do can confirm that Authentik displays the correct external IP address of my test "attacker".

The only thing which "breaks" the brute force attemp is to close the browser and reopen it.
Then I get a "page not found" information but not an "access denied".

**Comment by jay-kub** [comment]
I was able to resolve this by removing the password stage from my identification stage (default-authentication-identification). This will remove the password field from the login screen, so you then need to add a password stage after identification. To do this, select your authentication flow (default-authentication-flow), switch to the stage bindings tab, and create and bind a new password stage after the identification stage.

This appears to be a duplicate of #10196.

**Comment by netsho** [comment]
The issue still persists after latest release `2025.4.0`.
The user cannot go below the reputation threshold set in the settings, `5` by default. But when reached, the user isn't banned or blocked.
Is there anyway to make it while having password stage in identification stage ?

**Comment by Datenschmutz** [comment]
Issue still exists

**Comment by jay-kub** [comment]
> Issue still exists

It does, but since this is a duplicate the issue should be closed by @Dental1347.

**Comment by projetcrypto61-sketch** [comment]
Same issue here

**Comment by ferryversteeg** [comment]
Same issue

**Comment by projetcrypto61-sketch** [comment]
With the new version 2025.10 it worked for me

**Comment by jay-kub** [comment]
This is a closed issue--commenting on it is not useful. Follow the open issue #10196.
