### ISSUE TITLE
2024.12.1 seems to break outpost websocket completly

### ISSUE THREAD

**Issue by DunklerPhoenix** [goauthentik/authentik#12464]
**Describe the bug**
since the websocket url bug fix in 2024.12.1 outpost websockets cant connect to authentik anymore.
I tried it with slash at the end of the authentik url  and without slash.

The outposts themself seems to work. I can use them to connect to my applications.

**To Reproduce**

1. update to 2024.12.1
2. go to outpost
3. see all unavailable

**Expected behavior**
outposts can connect to authentik

**Screenshots**
![image](https://github.com/user-attachments/assets/5f668ad8-02a9-4c8e-8073-7226b28519fb)

**Logs**
`authentik-proxy-1  | {"error":"websocket: bad handshake","event":"failed to connect websocket","level":"warning","logger":"authentik.outpost.ak-api-controller","timestamp":"2024-12-23T18:20:18Z"}`

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.12.1
-   Deployment: docker compose

**Comment by systemdan5** [comment]
I can confirm this bug on my end as well. Reverting outposts back to 2024.10.5 fixes it.

2024.10.5
![outpost 10](https://github.com/user-attachments/assets/9ec73e19-e1a1-404e-82c1-67c257e0b695)

2024.12.1
![outpost 12](https://github.com/user-attachments/assets/2d2604af-a362-4c84-82e7-1047ab575fbe)

**Comment by krim404** [comment]
Have the same issue since version 2024.12.0, especially on the LDAP outpost.
error is pretty easy: there is something wrong with the builder for the wss string:
```
{"error":"parse \"wss://authentik.local:9443ws/outpost/d977a462-d5bb-431f-94ca-138a99d09787/?attempt=1\": invalid port \":9443ws\" after host","event":"failed to connect websocket","level":"warning","logger":"authentik.outpost.ak-api-controller","timestamp":"2024-12-23T20:02:23Z"}
```

**Comment by lucas-dclrcq** [comment]
Same issue on Kubernetes : 

<img width="1233" alt="Capture d’écran 2024-12-24 à 09 53 39" src="https://github.com/user-attachments/assets/cc0a7bb2-ac70-462a-9714-fc53e55e6432" />

**Comment by tuxmainy** [comment]
Hi everyone,
nice that this got fixed that fast. But I wonder if there is any workaround for now? Or should I stay at 2024.12.0 until this fix gets released?

TBH I didn't understood the problem fully. So, sry if the answer is obvious :)

regards
Daniel

**Comment by BeryJu** [comment]
you can use ghcr.io/goauthentik/dev-server:gh-version-2024.12 until a fixed version is released

**Comment by DunklerPhoenix** [comment]
I tried it with that server version([09b3a1d](https://github.com/goauthentik/authentik/commit/09b3a1d0bd3de630bde743ef8e4b25fcd109830d)), but still get the same errors. Do I need also to update the proxy?

**Comment by bartowski1182** [comment]
Just upgraded to 2024.12.1 and noticed this in my logs, any concerns if everything seems to be working fine? Relatively safe to ignore until the fix is released?

**Comment by DunklerPhoenix** [comment]
They outposts stop working after some hours. I'll tried everything, even to create one with the broken ssh outpost config, but nothing works...
I revert back

**Comment by boomam** [comment]
Just to add to the list of deplyoment with the issue - 2024.10.5 to 2024.12.1, same issue across all outposts.  
Continued log entries in the outposts logs as follows - 
```
{"error":"websocket: bad handshake","event":"failed to connect websocket","level":"warning","logger":"authentik.outpost.ak-api-controller","timestamp":"2024-12-28T23:55:56Z"}
{"event":"waiting 2 seconds to reconnect","level":"info","logger":"authentik.outpost.ak-api-controller","timestamp":"2024-12-28T23:55:56Z"}
```

**Comment by Miladiir** [comment]
https://github.com/goauthentik/authentik/issues/12464#issuecomment-2560220530

Can confirm that downgrading worked for ldap outpost. Currently using dev-server until new release becomes available.

**Comment by jtdroste** [comment]
Also adding this here / echo-ing @boomam . Latest version (2024.12.1), and still seeing the bad handshake / reconnect issue via the embeded outpost. Installed recently via the helm chart, no deviations.

Should this be re-opened, or a new issue created?

**Comment by Miladiir** [comment]
@jtdroste Fixed in next version, this is why the issue is closed. We need to be patient.
Downgrade your proxy/ldap containers to last 2024.10.x release and upgrade worker and server containers to dev-server latest version.

**Comment by Dav-Git** [comment]
If I'm following this correctly the issue will be fixed with release 2024.12.2.
Given that the corresponding fix was merged 2 weeks ago and that this is a major functionality breaking failure, I really hope that this release will be available soon to make the dev-server workaround (which might not always be practical nor desired) obsolete.

**Comment by tuxmainy** [comment]
Thanks for release 2024.12.2. Can confirm it works again.
