### ISSUE TITLE
No workers connected 2025.10.2

### ISSUE THREAD

**Issue by Deniom3** [goauthentik/authentik#18292]
### Describe the bug

In versions 2025.10.1 and 2025.10.2, the worker is displayed as not connected. 
At the same time, the worker logs continue to flow and no problems with the authenticator's operation were noticed.
The interface displays the following message: No workers connected. Background tasks will not run.

Rolling back to version 2025.10.0 solves the problem

### How to reproduce

Update using the official docker compose file

The following environment parameters are set
```
PG_PASS=secret
AUTHENTIK_SECRET_KEY=secret2
# SMTP Host Emails are sent to
AUTHENTIK_EMAIL__HOST=smtp.gmail.com
AUTHENTIK_EMAIL__PORT=465
AUTHENTIK_EMAIL__USERNAME=mail@gmail.com
AUTHENTIK_EMAIL__PASSWORD='pasword'
AUTHENTIK_EMAIL__FROM=admin@domein.ru
# Use StartTLS
AUTHENTIK_EMAIL__USE_TLS=false
# Use SSL
AUTHENTIK_EMAIL__USE_SSL=true
AUTHENTIK_EMAIL__TIMEOUT=10
```

### Expected behavior

Correct display that the worker is running

### Screenshots

<img width="769" height="550" alt="Image" src="https://github.com/user-attachments/assets/192389c5-bbc8-4b3c-90ff-0e128e98c50c" />

### Deployment Method

Docker

### Version

2025.10.2

### Relevant log output

```shell
2025-11-20T16:19:53.278789991Z INF app_name=authentik.stages.email domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.stages.email.tasks pid=7 schema_name=public timestamp=2025-11-20T16:19:53.278487

2025-11-20T16:19:53.279419369Z INF app_name=authentik.stages.identification domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.stages.identification.signals pid=7 schema_name=public timestamp=2025-11-20T16:19:53.279068

2025-11-20T16:19:53.279777480Z INF app_name=authentik.stages.invitation domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.stages.invitation.signals pid=7 schema_name=public timestamp=2025-11-20T16:19:53.279553

2025-11-20T16:19:53.280571553Z INF app_name=authentik.stages.prompt domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.stages.prompt.signals pid=7 schema_name=public timestamp=2025-11-20T16:19:53.280225

2025-11-20T16:19:53.281963870Z INF app_name=authentik.stages.user_write domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.stages.user_write.signals pid=7 schema_name=public timestamp=2025-11-20T16:19:53.281655

2025-11-20T16:19:53.285252806Z INF app_name=authentik.tasks.schedules domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.tasks.schedules.signals pid=7 schema_name=public timestamp=2025-11-20T16:19:53.284975

2025-11-20T16:19:53.301978105Z INF app_name=authentik.blueprints domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.blueprints.tasks pid=7 schema_name=public timestamp=2025-11-20T16:19:53.301660

2025-11-20T16:19:53.304405545Z INF app_name=authentik.enterprise.policies.unique_password domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.policies.unique_password.tasks pid=7 schema_name=public timestamp=2025-11-20T16:19:53.304082

2025-11-20T16:19:53.305421850Z INF app_name=authentik.enterprise.policies.unique_password domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.policies.unique_password.signals pid=7 schema_name=public timestamp=2025-11-20T16:19:53.305170

2025-11-20T16:19:53.307846837Z INF app_name=authentik.enterprise.providers.google_workspace domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.providers.google_workspace.tasks pid=7 schema_name=public timestamp=2025-11-20T16:19:53.307527

2025-11-20T16:19:53.308973812Z INF app_name=authentik.enterprise.providers.google_workspace domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.providers.google_workspace.signals pid=7 schema_name=public timestamp=2025-11-20T16:19:53.308718

2025-11-20T16:19:53.311136407Z INF app_name=authentik.enterprise.providers.microsoft_entra domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.providers.microsoft_entra.tasks pid=7 schema_name=public timestamp=2025-11-20T16:19:53.310875

2025-11-20T16:19:53.312239188Z INF app_name=authentik.enterprise.providers.microsoft_entra domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.providers.microsoft_entra.signals pid=7 schema_name=public timestamp=2025-11-20T16:19:53.311981

2025-11-20T16:19:53.314244107Z INF app_name=authentik.enterprise.providers.scim domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.providers.scim.signals pid=7 schema_name=public timestamp=2025-11-20T16:19:53.313980

2025-11-20T16:19:53.317093536Z INF app_name=authentik.enterprise.providers.ssf domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.providers.ssf.tasks pid=7 schema_name=public timestamp=2025-11-20T16:19:53.316807

2025-11-20T16:19:53.319470212Z INF app_name=authentik.enterprise.providers.ssf domain_url=null event=Imported related module logger=authentik.blueprints.apps module=authentik.enterprise.providers.ssf.signals pid=7 schema_name=public timestamp=2025-11-20T16:19:53.319187

2025-11-20T16:19:55.424272749Z === Starting migration

2025-11-20T16:19:56.321921753Z Operations to perform:

2025-11-20T16:19:56.321986504Z   Apply all migrations: auth, authentik_blueprints, authentik_brands, authentik_core, authentik_crypto, authentik_enterprise, authentik_events, authentik_flows, authentik_outposts, authentik_policies, authentik_policies_dummy, authentik_policies_event_matcher, authentik_policies_expiry, authentik_policies_expression, authentik_policies_geoip, authentik_policies_password, authentik_policies_reputation, authentik_policies_unique_password, authentik_providers_google_workspace, authentik_providers_ldap, authentik_providers_microsoft_entra, authentik_providers_oauth2, authentik_providers_proxy, authentik_providers_rac, authentik_providers_radius, authentik_providers_saml, authentik_providers_scim, authentik_providers_ssf, authentik_rbac, authentik_sources_kerberos, authentik_sources_ldap, authentik_sources_oauth, authentik_sources_plex, authentik_sources_saml, authentik_sources_scim, authentik_sources_telegram, authentik_stages_authenticator_duo, authentik_stages_authenticator_email, authentik_stages_authenticator_endpoint_gdtc, authentik_stages_authenticator_sms, authentik_stages_authenticator_static, authentik_stages_authenticator_totp, authentik_stages_authenticator_validate, authentik_stages_authenticator_webauthn, authentik_stages_captcha, authentik_stages_consent, authentik_stages_deny, authentik_stages_dummy, authentik_stages_email, authentik_stages_identification, authentik_stages_invitation, authentik_stages_mtls, authentik_stages_password, authentik_stages_prompt, authentik_stages_redirect, authentik_stages_source, authentik_stages_user_delete, authentik_stages_user_login, authentik_stages_user_logout, authentik_stages_user_write, authentik_tasks, authentik_tasks_schedules, authentik_tenants, contenttypes, django_channels_postgres, django_postgres_cache, guardian, sessions

2025-11-20T16:19:56.912050674Z Running migrations:

2025-11-20T16:19:56.912088023Z   No migrations to apply.

2025-11-20T16:20:03.311987098Z System check identified no issues (4 silenced).

2025-11-20T16:20:03.313521376Z INF domain_url=null event=releasing database lock logger=lifecycle.migrate pid=7 schema_name=public timestamp=2025-11-20T16:20:03.312925

2025-11-20T16:20:34.532341804Z INF event=Dramatiq '1.17.1' is booting up. logger=dramatiq.MainProcess timestamp=2025-11-20T16:20:34.531988

2025-11-20T16:20:34.533191665Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=0a6d0379-5098-439d-9acf-679fcb05d6e7 task_name=authentik.outposts.tasks.outpost_controller timestamp=2025-11-20T16:20:06.265992

2025-11-20T16:20:34.533424896Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=94eb1040-b28c-41e4-baa2-4a0aba4fe0d9 task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:06.286944

2025-11-20T16:20:34.533464047Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=8ecae0a5-2399-4f5e-b649-bd8b72ace8f1 task_name=authentik.outposts.tasks.outpost_controller timestamp=2025-11-20T16:20:06.309080

2025-11-20T16:20:34.533472162Z INF domain_url=null event=Provider changed, rebuilding permissions and sending update logger=authentik.outposts.signals outpost=authentik Embedded Outpost pid=90 provider=prowlarr schema_name=public timestamp=2025-11-20T16:20:06.554697

2025-11-20T16:20:34.533478840Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=83aa7aa9-6b88-45d2-acfa-9a93298e2e77 task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:10.128273

2025-11-20T16:20:34.533499826Z INF domain_url=null event=Provider changed, rebuilding permissions and sending update logger=authentik.outposts.signals outpost=authentik Embedded Outpost pid=90 provider=plex schema_name=public timestamp=2025-11-20T16:20:10.153110

2025-11-20T16:20:34.533505883Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=5f085d1b-c5b7-4209-a440-12680739a1ac task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:13.315033

2025-11-20T16:20:34.533511483Z INF domain_url=null event=Provider changed, rebuilding permissions and sending update logger=authentik.outposts.signals outpost=authentik Embedded Outpost pid=90 provider=sonarr schema_name=public timestamp=2025-11-20T16:20:13.332995

2025-11-20T16:20:34.533797663Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=7f707689-41d2-46d5-a2cd-4c47077bd2c5 task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:16.512294

2025-11-20T16:20:34.533810290Z INF domain_url=null event=Provider changed, rebuilding permissions and sending update logger=authentik.outposts.signals outpost=authentik Embedded Outpost pid=90 provider=couchdb schema_name=public timestamp=2025-11-20T16:20:16.695180

2025-11-20T16:20:34.533816251Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=869834b1-4c86-4b81-aa85-a0ffe3d631a2 task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:19.490074

2025-11-20T16:20:34.533821615Z INF domain_url=null event=Provider changed, rebuilding permissions and sending update logger=authentik.outposts.signals outpost=authentik Embedded Outpost pid=90 provider=radarr schema_name=public timestamp=2025-11-20T16:20:19.527009

2025-11-20T16:20:34.533826410Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=b72f4878-067c-4ecd-9904-4b41c38d6aaa task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:22.022670

2025-11-20T16:20:34.533831232Z INF domain_url=null event=Provider changed, rebuilding permissions and sending update logger=authentik.outposts.signals outpost=authentik Embedded Outpost pid=90 provider=dockge schema_name=public timestamp=2025-11-20T16:20:22.038449

2025-11-20T16:20:34.533836464Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=274490d3-0e35-47c1-af0a-e477a16cb8eb task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:24.763106

2025-11-20T16:20:34.533850591Z INF domain_url=null event=Provider changed, rebuilding permissions and sending update logger=authentik.outposts.signals outpost=authentik Embedded Outpost pid=90 provider=prometheus schema_name=public timestamp=2025-11-20T16:20:24.779797

2025-11-20T16:20:34.533855724Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=99c59316-4ad3-40a2-a9bd-4b4ba06aab34 task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:27.594753

2025-11-20T16:20:34.533860545Z INF domain_url=null event=Provider changed, rebuilding permissions and sending update logger=authentik.outposts.signals outpost=authentik Embedded Outpost pid=90 provider=uptime kuma schema_name=public timestamp=2025-11-20T16:20:27.613444

2025-11-20T16:20:34.533865169Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=c91bc6ae-362e-45b4-9f02-7f133ccf6e0b task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:30.395728

2025-11-20T16:20:34.533869814Z INF domain_url=null event=Provider changed, rebuilding permissions and sending update logger=authentik.outposts.signals outpost=authentik Embedded Outpost pid=90 provider=vaultwarden schema_name=public timestamp=2025-11-20T16:20:30.432424

2025-11-20T16:20:34.533874488Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=2d67a416-1913-4f00-a6cc-29446a1e8b3a task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:33.540473

2025-11-20T16:20:34.533879718Z INF domain_url=null event=Provider changed, rebuilding permissions and sending update logger=authentik.outposts.signals outpost=authentik Embedded Outpost pid=90 provider=traefik schema_name=public timestamp=2025-11-20T16:20:33.578679

2025-11-20T16:20:37.558654464Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=49f96861-a80c-4b00-bc57-5c709c5d22d3 task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:37.558008

2025-11-20T16:20:38.123984388Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=96879771-2dc1-4dae-a99a-bb3a370c730d task_name=authentik.outposts.tasks.outpost_connection_discovery timestamp=2025-11-20T16:20:38.122694

2025-11-20T16:20:38.145388517Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=5553dba4-74e5-400f-9a4c-239fd6a4751c task_name=authentik.blueprints.v1.tasks.blueprints_discovery timestamp=2025-11-20T16:20:38.144858

2025-11-20T16:20:38.177007104Z INF domain_url=null event=Task enqueued logger=authentik.tasks.middleware pid=90 schema_name=public task_id=6fe78cd8-5af5-452e-a28e-e1df46d16dfd task_name=authentik.blueprints.v1.tasks.clear_failed_blueprints timestamp=2025-11-20T16:20:38.175686

2025-11-20T16:20:38.247520594Z INF domain_url=null event=authentik Core Worker finished starting logger=authentik.root.signals pid=90 schema_name=public timestamp=2025-11-20T16:20:38.247013 took_s=34.688087

2025-11-20T16:20:38.317197836Z INF event=Worker process is ready for action. logger=dramatiq.WorkerProcess(0) timestamp=2025-11-20T16:20:38.316496

2025-11-20T16:20:38.329018446Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:38.328531

2025-11-20T16:20:38.444182040Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:38.440676

2025-11-20T16:20:38.478647140Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:38.477854

2025-11-20T16:20:38.534198321Z INF domain_url=null event=Task started logger=authentik.tasks.middleware pid=90 schema_name=public task_id=83aa7aa9-6b88-45d2-acfa-9a93298e2e77 task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:38.533744

2025-11-20T16:20:38.546029608Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:38.545574

2025-11-20T16:20:38.562999389Z INF domain_url=null event=Task started logger=authentik.tasks.middleware pid=90 schema_name=public task_id=5f085d1b-c5b7-4209-a440-12680739a1ac task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:38.560600

2025-11-20T16:20:38.579603536Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:38.579008

2025-11-20T16:20:38.612580406Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:38.610053

2025-11-20T16:20:38.635057788Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:38.634058

2025-11-20T16:20:38.662666439Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:38.662131

2025-11-20T16:20:38.710494192Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:38.709385

2025-11-20T16:20:38.779480922Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:38.778974

2025-11-20T16:20:38.884334917Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:38.883577

2025-11-20T16:20:39.128082796Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:39.127475

2025-11-20T16:20:39.497200361Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:39.495933

2025-11-20T16:20:40.094835380Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:40.093410

2025-11-20T16:20:41.024471025Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:41.023587

2025-11-20T16:20:41.539441749Z INF domain_url=null event=Task finished exc=null logger=authentik.tasks.middleware pid=90 schema_name=public task_id=83aa7aa9-6b88-45d2-acfa-9a93298e2e77 task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:41.538963

2025-11-20T16:20:41.656101108Z INF domain_url=null event=Task started logger=authentik.tasks.middleware pid=90 schema_name=public task_id=94eb1040-b28c-41e4-baa2-4a0aba4fe0d9 task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:41.653755

2025-11-20T16:20:41.802127660Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:41.801444

2025-11-20T16:20:41.822561931Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:41.822040

2025-11-20T16:20:41.841143843Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:41.840654

2025-11-20T16:20:41.869800797Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:41.869292

2025-11-20T16:20:41.891225001Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:41.889930

2025-11-20T16:20:41.938199201Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:41.937612

2025-11-20T16:20:42.007565764Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:42.006662

2025-11-20T16:20:42.110199295Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:42.109721

2025-11-20T16:20:42.298333043Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:42.297825

2025-11-20T16:20:42.695771147Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:42.691714

2025-11-20T16:20:43.700225811Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:43.698461

2025-11-20T16:20:44.604177196Z INF domain_url=null event=Task finished exc=null logger=authentik.tasks.middleware pid=90 schema_name=public task_id=5f085d1b-c5b7-4209-a440-12680739a1ac task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:44.602956

2025-11-20T16:20:44.699019301Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:44.698554

2025-11-20T16:20:44.730504337Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:44.729305

2025-11-20T16:20:44.740548667Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:44.739965

2025-11-20T16:20:44.759552741Z INF domain_url=null event=Task started logger=authentik.tasks.middleware pid=90 schema_name=public task_id=c91bc6ae-362e-45b4-9f02-7f133ccf6e0b task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:44.758909

2025-11-20T16:20:44.763020425Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:44.762617

2025-11-20T16:20:44.793564733Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:44.792219

2025-11-20T16:20:44.842254520Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:44.841752

2025-11-20T16:20:44.912776319Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:44.910573

2025-11-20T16:20:45.037959795Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:45.032562

2025-11-20T16:20:45.244048337Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:45.243100

2025-11-20T16:20:45.627807235Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:45.627304

2025-11-20T16:20:46.336581845Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:46.331956

2025-11-20T16:20:46.938702895Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:46.937143

2025-11-20T16:20:47.864256816Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:47.863388

2025-11-20T16:20:48.468604519Z INF domain_url=null event=Sent 0 scheduled tasks logger=django_dramatiq_postgres.scheduler pid=90 schema_name=public timestamp=2025-11-20T16:20:48.467028

2025-11-20T16:20:49.086423546Z INF domain_url=null event=Task finished exc=null logger=authentik.tasks.middleware pid=90 schema_name=public task_id=94eb1040-b28c-41e4-baa2-4a0aba4fe0d9 task_name=authentik.outposts.tasks.outpost_send_update timestamp=2025-11-20T16:20:49.085863

2025-11-20T16:20:49.279058817Z INF domain_url=null event=Task started logger=authentik.tasks.middleware pid=90 schema_name=public task_id=8ecae0a5-2399-4f5e-b649-bd8b72ace8f1 task_name=authentik.outposts.tasks.outpost_controller timestamp=2025-11-20T16:20:49.277708
```

**Comment by BeryJu** [comment]
we're looking into it

**Comment by Kodalinq** [comment]
+1 Same issue here on version 2025.10.2

**Comment by FoXiCZEk** [comment]
+1 Same issue after update 2025.10.1 -> 2025.10.2

**Comment by boesr** [comment]
+1 I'm not sure if this is relevant, but I see some database errors in the log when the displayed worker count does not match the running ones. The worker restarts afterwards, but that does not seem to be recognised by Authentik. Also, we have eight workers, and at first, four of them always get lost, and then another four.

```bash
Nov 26 09:58:12 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Consumer encountered a connection error: the connection
 is closed", "level": "critical", "logger": "dramatiq.worker.ConsumerThread(default)", "timestamp": "2025-11-26T08:58:12.639132"}
Nov 26 09:58:12 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Restarting consumer in 3.00 seconds.", "level": "info",
 "logger": "dramatiq.worker.ConsumerThread(default)", "timestamp": "2025-11-26T08:58:12.639200"}
Nov 26 09:58:14 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Sending signal 15 to subprocesses...", "level": "info",
 "logger": "dramatiq.MainProcess", "timestamp": "2025-11-26T08:58:14.069112"}
Nov 26 09:58:14 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Stopping fork process...", "level": "info", "logger": "
dramatiq.ForkProcess(0)", "timestamp": "2025-11-26T08:58:14.069087"}
Nov 26 09:58:14 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Stopping fork process...", "level": "info", "logger": "
dramatiq.ForkProcess(0)", "timestamp": "2025-11-26T08:58:14.069270"}
Nov 26 09:58:14 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Stopping fork process...", "level": "info", "logger": "
dramatiq.ForkProcess(1)", "timestamp": "2025-11-26T08:58:14.069112"}
Nov 26 09:58:14 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Stopping fork process...", "level": "info", "logger": "
dramatiq.ForkProcess(1)", "timestamp": "2025-11-26T08:58:14.069264"}
Nov 26 09:58:14 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Stopping worker process...", "level": "info", "logger":
 "dramatiq.WorkerProcess(0)", "timestamp": "2025-11-26T08:58:14.069271"}
Nov 26 09:58:14 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Stopping worker process...", "level": "info", "logger":
 "dramatiq.WorkerProcess(0)", "timestamp": "2025-11-26T08:58:14.069134"}
Nov 26 09:58:14 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Stopping fork process...", "level": "info", "logger": "
dramatiq.ForkProcess(2)", "timestamp": "2025-11-26T08:58:14.069315"}
Nov 26 09:58:14 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Shutting down...", "level": "info", "logger": "dramatiq
.worker.Worker", "timestamp": "2025-11-26T08:58:14.588770"}
Nov 26 09:58:15 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Worker has been shut down.", "level": "info", "logger":
 "dramatiq.worker.Worker", "timestamp": "2025-11-26T08:58:15.641996"}
Nov 26 09:58:18 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Loaded config", "level": "debug", "logger": "authentik.
lib.config", "timestamp": 1764147498.4002674, "file": "/authentik/lib/default.yml"}
Nov 26 09:58:18 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Loaded environment variables", "level": "debug", "logge
r": "authentik.lib.config", "timestamp": 1764147498.400588, "count": 15}
Nov 26 09:58:18 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Starting authentik bootstrap", "level": "info", "logger
": "authentik.lib.config", "timestamp": 1764147498.59797}
Nov 26 09:58:18 authentik.my.domain.de dadbddf7d469[1727]: {"event": "PostgreSQL connection successful", "level": "info", "lo
gger": "authentik.lib.config", "timestamp": 1764147498.6179485}
Nov 26 09:58:18 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Finished authentik bootstrap", "level": "info", "logger
": "authentik.lib.config", "timestamp": 1764147498.618072}
Nov 26 09:58:18 authentik.my.domain.de dadbddf7d469[1727]: {"event": "Booting authentik", "level": "info", "logger": "authent
ik.lib.config", "timestamp": 1764147498.9925983, "version": "2025.10.2"}
```

**Comment by SleepyShoggoth** [comment]
+1 Same issue after upgrading from 2025.10 -> 2025.10.2

**Comment by VincentBean** [comment]
+1 Same issue after update 2025.10.1 -> 2025.10.2

**Comment by rissson** [comment]
We know, but we can't reproduce. No need to keep commenting. This is simply a visual error (i.e. the data from the worker is not reported correctly), but the workers should still behave normally.

**Comment by TommyTran732** [comment]
In my case, it does happen, but only after about a day. So the step to reproduce would be to leave both the server and worker running for about a day or two

**Comment by Zer0ot** [comment]
+1 Same Issue 2025.10.1 -> 2025.10.2

worker instance count: 2
deployment: k8s / helm 2025.10.2

Service Fully Operational

Edit 1:
If this is the Task:

<img width="1294" height="566" alt="Image" src="https://github.com/user-attachments/assets/cd1a663e-49f0-47e6-aa25-a1d15cd981f4" />

No effect:

<img width="707" height="162" alt="Image" src="https://github.com/user-attachments/assets/fbcaf18e-d69d-4d89-b391-9b0866f538d9" />

Edit 2:
Possible Root Cause: Missing Metrics?

<img width="1724" height="409" alt="Image" src="https://github.com/user-attachments/assets/e16891ad-f58e-4d0d-adaa-7d0a0e901ba4" />

<img width="522" height="312" alt="Image" src="https://github.com/user-attachments/assets/b5185be6-dbb9-44a5-bec9-3aaff2fdca73" />

**Comment by TommyTran732** [comment]
Likely related: https://github.com/goauthentik/authentik/issues/18546

My Postgres container does get update more frequently than my Authentik container currently, so this might be the issue.

**Comment by oed-hamelf** [comment]
Hello everyone,

We can confirm this issue.
In our environment we are using the cloudnative-pg operator, rancher systemupgrade-controller and kured.
By this we ensure all nodes get OS updates and necessary reboots.

What happens is this:

1. systemupgrade-controller patches the OS and maybe a reboot is required ("/var/run/reboot-required" is present)
2. kured set the node cordon and the Postgres will perform a switchover, based on certain configuration.
3. Authentik worker lost connection to the Postgres and aren't able to reconnect.

So, what from what we are seeing the worker are down and not functional at this point.
Thanks to the information in #18546 we deployed a custom livenessprobe configmap as workaround.

**Comment by badsmoke** [comment]
This also happens in the Docker environment when using, for example, Watchtower—a service that automatically updates containers.

**Comment by nkamenar** [comment]
I am also experiencing this in my Docker Swarm setup on 2025.10.2. As previously reported the worker container is processing tasks just fine so this appear to just be a UI bug.

**Comment by Zer0ot** [comment]
Updated to **2025.10.3** -> Issue Persists

Admin Overview showing 0 Workers, while tasks are processes just fine, worker pods up and running.

**Comment by Harrisonechris** [comment]
Still encountering this issue, updated to 2025.10.3, still reporting no workers.

**Comment by baragoon** [comment]
fresh 2025.10.3 install, 1st day was fine but today I see 0 workers, weird.

**Comment by HeyItsJono** [comment]
Same issue on 2025.12.1

**Comment by MaxPayne1776** [comment]
Still no Workers since 2025.10, running via docker compose.

<img width="1513" height="675" alt="Image" src="https://github.com/user-attachments/assets/0455384b-03a6-42cc-925e-c5eb25fdfbd7" />

**Comment by joachimtingvold** [comment]
Same issue here. Upgraded from 2025.6 -> 2025.8 -> 2025.10 today.

I might've upgraded from 2025.8 to 2025.10 too quickly? (i.e. I only pulled 2025.8, started, tested login in to Authentik, all status was green/OK, stopped and upgraded to 2025.10).

Upgraded a separate instance the same versions the other day (2025.6->8->10), but stayed on 2025.8 for longer before upgrading to 2025.10, and everything works fine there... not sure if related or not.

**Comment by rissson** [comment]
Yeah, we still are having a hard time reproducing it, but we think it might occur when some DB error happens. We're still looking into it.

**Comment by oed-hamelf** [comment]
> Yeah, we still are having a hard time reproducing it, but we think it might occur when some DB error happens. We're still looking into it.

Hi there.
Ist not only happening on DB erros, also if the primary instance of a clusters performs a swichover, i.e. in case of maintenacne.
The application should be able establish connection again assoon the primary has switched.
The workes seems not to support this.

**Comment by kreutpet** [comment]
Did upgrade to 2025.12.2 and still have no workers connected error.

Anything i can do to investigate the root cause ?
i could not find some obvious error in the logs

**Comment by MaxPayne1776** [comment]
I was able to resolve this error. I am posting the steps I took here in case it helps others. As always, make sure you have a backup of your database before proceeding.

These steps are for an authentik deployment via docker compose.

1. Connect to the Docker container's console where the database resides. (authentik-postgresql-1 for me)
2. From within the console, connect to the database. (psql -U authentik -d authentik)
3. Run the following maintenance commands on the database, taken from: (https://www.postgresql.org/docs/17/maintenance.html)

> VACUUM;
VACUUM ANALYZE;
VACUUM FULL;
REINDEX DATABASE authentik;

Note the trailing ; at the end of each command.

Once complete, exit from the console and restart all authentik Docker containers. I am not sure which command actually resolved the issue for me, as I was throwing everything at the wall at that point.

I ran these commands while on 2025.12.1 and after upgrading to 2025.12.2 the "no workers" error has not reappeared.

**Comment by christensenjairus** [comment]
> I was able to resolve this error. I am posting the steps I took here in case it helps others. As always, make sure you have a backup of your database before proceeding.
> 
> These steps are for an authentik deployment via docker compose.
> 
> 1. Connect to the Docker container's console where the database resides. (authentik-postgresql-1 for me)
> 2. From within the console, connect to the database. (psql -U authentik -d authentik)
> 3. Run the following maintenance commands on the database, taken from: (https://www.postgresql.org/docs/17/maintenance.html)
> 
> > VACUUM;
> > VACUUM ANALYZE;
> > VACUUM FULL;
> > REINDEX DATABASE authentik;
> 
> Note the trailing ; at the end of each command.
> 
> Once complete, exit from the console and restart all authentik Docker containers. I am not sure which command actually resolved the issue for me, as I was throwing everything at the wall at that point.
> 
> I ran these commands while on 2025.12.1 and after upgrading to 2025.12.2 the "no workers" error has not reappeared.

This did not fix it for me on k8s. But I haven't had workers showing as connected since 2025.10.

**Comment by Malaber** [comment]
As a workaround I resorted to adding this in my `podman-compose.yml`:

```
services:
  worker:
    # ...
    # worker options 
    # ...
    healthcheck:
      test:
        - "CMD-SHELL"
        - "python3 /manage.py shell -c \"from django.utils import timezone; from datetime import timedelta; from authentik.tasks.models import WorkerStatus; import os, sys; exists = WorkerStatus.objects.filter(hostname=os.uname()[1], last_seen__gte=timezone.now() - timedelta(minutes=2)).exists(); sys.exit(0 if exists else 1)\""
      start_period: 60s
      interval: 100s
      retries: 2
      timeout: 5s
```

This is essentially the check from [here](https://github.com/goauthentik/authentik/blob/ff87929dcf9ff03a2582cc829a34287e936b797b/authentik/tasks/api/workers.py#L34) where the frontend also checks the Workers status.

At least for my setup, the WorkerStatus objects were not written after some time. Manually starting `WorkerStatusMiddleware.run()` wrote them back into the database, which does probably not fix the underlying problem. 

I don't understand the code enough to say what failed and I also don't know when it failed, so I cannot look into the logs to see if there was an error that made the worker quit the `WorkerStatusMiddleware.run()` method. It just seems to not be running anymore. 

Restarting the container via the compose healthcheck should fix that. 

I do not know how resource intensive the check is, I have just implemented it that way and will be testing, if that fixes the problem (for now).

Running `ak healtcheck` on a worker that is reported as offline in the frontend results in the following (wrong?) result:
```
{"event":"checking health","level":"debug","mode":"worker","timestamp":"2026-02-03T13:59:48Z"}
{"event":"successfully checked health","level":"info","timestamp":"2026-02-03T13:59:48Z"}
# exit 0
```

I run authentik using podman and use a managed postgres service.

**Comment by wv-opt-ai** [comment]
> I was able to resolve this error. I am posting the steps I took here in case it helps others. As always, make sure you have a backup of your database before proceeding.
> 
> These steps are for an authentik deployment via docker compose.
> 
> 1. Connect to the Docker container's console where the database resides. (authentik-postgresql-1 for me)
> 2. From within the console, connect to the database. (psql -U authentik -d authentik)
> 3. Run the following maintenance commands on the database, taken from: (https://www.postgresql.org/docs/17/maintenance.html)
> 
> > VACUUM;
> > VACUUM ANALYZE;
> > VACUUM FULL;
> > REINDEX DATABASE authentik;
> 
> Note the trailing ; at the end of each command.
> 
> Once complete, exit from the console and restart all authentik Docker containers. I am not sure which command actually resolved the issue for me, as I was throwing everything at the wall at that point.
> 
> I ran these commands while on 2025.12.1 and after upgrading to 2025.12.2 the "no workers" error has not reappeared.

This indeed did the trick for me, on 2025.12.3.

**Comment by Malaber** [comment]
As far as I understand the code, if there is a DB error in the [run method](https://github.com/goauthentik/authentik/blob/ff87929dcf9ff03a2582cc829a34287e936b797b/authentik/tasks/middleware.py#L238), it is not logged. And no mitigations other than closing DB connections are done. 
So, as far as I understand, if there is a ongoing DB error that would only be fixed by restarting the worker, the WorkerStatus is not written (which is good), but `ak healthcheck` does not catch that (which is bad) and therefore the worker stays offline.

About the VACUUM workaround above; 

> I was able to resolve this error. I am posting the steps I took here in case it helps others. As always, make sure you have a backup of your database before proceeding.
> 
> These steps are for an authentik deployment via docker compose.
> 
> Connect to the Docker container's console where the database resides. (authentik-postgresql-1 for me)
> From within the console, connect to the database. (psql -U authentik -d authentik)
> Run the following maintenance commands on the database, taken from: (https://www.postgresql.org/docs/17/maintenance.html)
> VACUUM;
> VACUUM ANALYZE;
> VACUUM FULL;
> REINDEX DATABASE authentik;
> 
> Note the trailing ; at the end of each command.
> 
> Once complete, exit from the console and restart all authentik Docker containers. I am not sure which command actually resolved the issue for me, as I was throwing everything at the wall at that point.

I think the restart just postpones the error until a later date, which fixes it in the meantime, but a simple restart would have sufficed. Or did only restarting without VACUUM etc. not help in your cases?

**Comment by MaxPayne1776** [comment]
> As far as I understand the code, if there is a DB error in the [run method](https://github.com/goauthentik/authentik/blob/ff87929dcf9ff03a2582cc829a34287e936b797b/authentik/tasks/middleware.py#L238), it is not logged. And no mitigations other than closing DB connections are done. So, as far as I understand, if there is a ongoing DB error that would only be fixed by restarting the worker, the WorkerStatus is not written (which is good), but `ak healthcheck` does not catch that (which is bad) and therefore the worker stays offline.
> 
> About the VACUUM workaround above;
> 
> > I was able to resolve this error. I am posting the steps I took here in case it helps others. As always, make sure you have a backup of your database before proceeding.
> > These steps are for an authentik deployment via docker compose.
> > Connect to the Docker container's console where the database resides. (authentik-postgresql-1 for me)
> > From within the console, connect to the database. (psql -U authentik -d authentik)
> > Run the following maintenance commands on the database, taken from: (https://www.postgresql.org/docs/17/maintenance.html)
> > VACUUM;
> > VACUUM ANALYZE;
> > VACUUM FULL;
> > REINDEX DATABASE authentik;
> > Note the trailing ; at the end of each command.
> > Once complete, exit from the console and restart all authentik Docker containers. I am not sure which command actually resolved the issue for me, as I was throwing everything at the wall at that point.
> 
> I think the restart just postpones the error until a later date, which fixes it in the meantime, but a simple restart would have sufficed. Or did only restarting without VACUUM etc. not help in your cases?

I had the error since 2025.10. Restarting the docker containers or even my whole VPS did not remove the error, even temporarily. Only after the maintenance commands I listed did the error go away.

PS. I am now on 2025.12.3 and the error has not reappeared.

**Comment by KaHooli** [comment]
> I was able to resolve this error. I am posting the steps I took here in case it helps others. As always, make sure you have a backup of your database before proceeding.
> 
> These steps are for an authentik deployment via docker compose.
> 
> 1. Connect to the Docker container's console where the database resides. (authentik-postgresql-1 for me)
> 2. From within the console, connect to the database. (psql -U authentik -d authentik)
> 3. Run the following maintenance commands on the database, taken from: (https://www.postgresql.org/docs/17/maintenance.html)
> 
> > VACUUM;
> > VACUUM ANALYZE;
> > VACUUM FULL;
> > REINDEX DATABASE authentik;
> 
> Note the trailing ; at the end of each command.
> 
> Once complete, exit from the console and restart all authentik Docker containers. I am not sure which command actually resolved the issue for me, as I was throwing everything at the wall at that point.
> 
> I ran these commands while on 2025.12.1 and after upgrading to 2025.12.2 the "no workers" error has not reappeared.

This also fixed the issue for me, currently on 2025.12.3.  I had been having this issue for months now but wasn't overly concerned as the logs seemed to indicate that the worker was working.

**Comment by HeyItsJono** [comment]
> I was able to resolve this error. I am posting the steps I took here in case it helps others. As always, make sure you have a backup of your database before proceeding.
> 
> These steps are for an authentik deployment via docker compose.
> 
>     1. Connect to the Docker container's console where the database resides. (authentik-postgresql-1 for me)
> 
>     2. From within the console, connect to the database. (psql -U authentik -d authentik)
> 
>     3. Run the following maintenance commands on the database, taken from: (https://www.postgresql.org/docs/17/maintenance.html)
> 
> 
> > VACUUM;
> > VACUUM ANALYZE;
> > VACUUM FULL;
> > REINDEX DATABASE authentik;
> 
> Note the trailing ; at the end of each command.
> 
> Once complete, exit from the console and restart all authentik Docker containers. I am not sure which command actually resolved the issue for me, as I was throwing everything at the wall at that point.
> 
> I ran these commands while on 2025.12.1 and after upgrading to 2025.12.2 the "no workers" error has not reappeared.

Ran this on 2025.12.3 and I still get the same error personally.

**Comment by joachimtingvold** [comment]
Upgraded another Authentik-instance. Went from 2025.6 to 2025.8, stayed there for a couple of weeks without any issue. Upgraded to 2025.10.3 today, and got the "no workers connected" issue. That means 2 out of my 4 Authentik-instances that was upgraded "2025.6 -> 2025.8 -> 2025.10" got this error. The first one has been in the failed state for a couple of weeks without change (even after restarting Authentik).

Both of these two "failed" instances was fixed with the `VACUUM/REINDEX`-steps mentioned above. None of the 4 instances has thus far been upgraded to 2025.12 (i.e. they are all currently 2025.10.3).

**Comment by joachimtingvold** [comment]
I also moved the Authentik-database from a Dockerized PostgreSQL 16 server, to a standalone PostgreSQL 17 server, without changing anything on the authentik server/worker containers (except restarting them with new env-variables for the new server). After this change, I got the "no workers connected" (prior to the database move, there was no issues). This means that the issue happened by only changing database aspects. Doing the `VACUUM/REINDEX`-steps on the new PostgreSQL 17 server resolved the issue once again.

**Comment by rissson** [comment]
Hello, thanks a lot for all the comments. We have been able to reproduce once, and not anymore since, without changing anything to the deployment where this occurred. We have a few improvements planned for the worker, including reworking the way we report the worker status. These are _not_ planned for 2026.2, so no need to comment that this is still happening on that version.

**Comment by joachimtingvold** [comment]
> I also moved the Authentik-database from a Dockerized PostgreSQL 16 server, to a standalone PostgreSQL 17 server, without changing anything on the authentik server/worker containers (except restarting them with new env-variables for the new server). After this change, I got the "no workers connected" (prior to the database move, there was no issues). This means that the issue happened by only changing database aspects. Doing the `VACUUM/REINDEX`-steps on the new PostgreSQL 17 server resolved the issue once again.

After a restart of the PostgreSQL-server, and without restarting the Authentik server/worker, the "no workers connected" issue is back again on this same instance/setup.

**Comment by joachimtingvold** [comment]
Seems like the issues are closely related to the database, and probably specifically after moving the Redis-logic into the PostgreSQL-database.

**Comment by kevinruffus** [comment]
> I was able to resolve this error. I am posting the steps I took here in case it helps others. As always, make sure you have a backup of your database before proceeding.
> 
> These steps are for an authentik deployment via docker compose.
> 
> 1. Connect to the Docker container's console where the database resides. (authentik-postgresql-1 for me)
> 2. From within the console, connect to the database. (psql -U authentik -d authentik)
> 3. Run the following maintenance commands on the database, taken from: (https://www.postgresql.org/docs/17/maintenance.html)
> 
> > VACUUM;
> > VACUUM ANALYZE;
> > VACUUM FULL;
> > REINDEX DATABASE authentik;
> 
> Note the trailing ; at the end of each command.
> 
> Once complete, exit from the console and restart all authentik Docker containers. I am not sure which command actually resolved the issue for me, as I was throwing everything at the wall at that point.
> 
> I ran these commands while on 2025.12.1 and after upgrading to 2025.12.2 the "no workers" error has not reappeared.

This worked for me as well.
2025.12.3 via docker compose.

**Comment by cheggerdev** [comment]
> > I was able to resolve this error. I am posting the steps I took here in case it helps others. As always, make sure you have a backup of your database before proceeding.
> > These steps are for an authentik deployment via docker compose.
> > 
> > 1. Connect to the Docker container's console where the database resides. (authentik-postgresql-1 for me)
> > 2. From within the console, connect to the database. (psql -U authentik -d authentik)
> > 3. Run the following maintenance commands on the database, taken from: (https://www.postgresql.org/docs/17/maintenance.html)
> > 
> > > VACUUM;
> > > VACUUM ANALYZE;
> > > VACUUM FULL;
> > > REINDEX DATABASE authentik;
> > 
> > 
> > Note the trailing ; at the end of each command.
> > Once complete, exit from the console and restart all authentik Docker containers. I am not sure which command actually resolved the issue for me, as I was throwing everything at the wall at that point.
> > I ran these commands while on 2025.12.1 and after upgrading to 2025.12.2 the "no workers" error has not reappeared.
> 
> This worked for me as well. 2025.12.3 via docker compose.

This worked for me, too.
2026.2.0 via docker compose.

**Comment by davepgreene** [comment]
This seems to be resolved in 2026.2.1.

**Comment by kevinruffus** [comment]
I don't remember if I bumped up yet, so I'll take a look.

I had it happen two days ago.

**Comment by cheggerdev** [comment]
Actually this issue remains reproducely when I set AUTHENTIK_WORKER__PROCESSES=4
Then I have no workers.

**Comment by christensenjairus** [comment]
When my workers are a incorrect version it almost works as expected 😆 

Worker on 2025.12.4, server on 2026.2.1

<img width="302" height="183" alt="Image" src="https://github.com/user-attachments/assets/6c626df5-c16f-4a75-9d35-eaf2a4b3a196" />

vs when they're the same version, both 2026.2.1

<img width="302" height="183" alt="Image" src="https://github.com/user-attachments/assets/a856ccfa-8f7c-48d0-bb53-428b9c6b732d" />

**Comment by micaheli** [comment]
I ran the psql commands above and that resolved it for me with the 2026.2.1 update.

**Comment by HeyItsJono** [comment]
Can confirm this issue is still present on 2026.2.1 despite running the psql commands above...

**Comment by cheggerdev** [comment]
To me the psql command above do help with `AUTHENTIK_WORKER__PROCESSES` set to 1 or 2.
They do not help when `AUTHENTIK_WORKER__PROCESSES` set to 4.

**Comment by dubyatp** [comment]
Mine seems to be a bit less consistent. When I go to the Authentik admin page, it starts off by showing there's "no workers" online, but when I refresh the page, it will say there's 2, and then I refresh again it says 3 (the actual number of workers I have)

For context i have a 3x3 HA configuration (3 server instances + 3 worker instances)

**Comment by shcherbak** [comment]
<img width="590" height="215" alt="Image" src="https://github.com/user-attachments/assets/141e82d9-7c79-4c64-9c85-0ae5c181bfe4" />
the same problem with v.2026.12

**Comment by FurkanVG** [comment]
<img width="813" height="197" alt="Image" src="https://github.com/user-attachments/assets/9cadd8b7-dd09-418c-b450-bfb95b1d7b49" />
Happens  again, my docker containers, especially the worker  one, shows no direct errors.

**Comment by johnkeates** [comment]
We're on Kubernetes, and it appears none of the tasks that need a fork are executed. The workers are functional and using default settings (1 server, 1 worker, clean database) shows it works, but when using an existing database and multiple instances none of the tasks in https://github.com/goauthentik/authentik/blob/version/2026.2.2/authentik/tasks/forks.py ever run.

I ended up using kubectl debug to edit forks.py and having it log, print and dump files in /tmp to show if any of the functions are actually called, but they aren't. The file itself does get imported (added a print for that too). 

Looking at https://github.com/goauthentik/authentik/blob/5249546862986202b901c2afd860992ec48c6ef6/authentik/tasks/middleware.py#L239 this should return the function so it can be executed in a separate thread, or get forked, but it just doesn't.

Edit: turns out it's most likely this issue https://github.com/python/cpython/issues/84559 where the threaded nature causes the forked workers to be stalled out. Since it appears to be a race condition in some cases (depending on what state the database socket is in) it also explains why this works on a near-empty fresh instance or why some people see different behaviour if the database was vacuumed/reindexed recently as the race condition might trip over itself less.

Edit2: I'm having a hard time digging in to where this is exactly happening; I can see the threads in the process being spawned and `ps` will show there are three idle ones (I suspect the health, metrics and status ones), but `py-spy` doesn't work with Python 3.14 and I can't get a debugger to work from inside a normal release container... In theory I could setup a dev environment, load a current database on to that and try it that way, but I wonder if that would produce too many differences between the problematic environment and the dev environment to really get to the bottom of this.

**Comment by Ryderjj89** [comment]
Yeah this is definitely still happening on 2026.2.2. I am not noticing any "issues" but it is weird to see this on the dashboard.

**Comment by HeyItsJono** [comment]
Confirmed fixed for me on `2026.5.3`
