### ISSUE TITLE
Default values for ENV properties to allow editing of user fields no longer works when disallowing one of them

### ISSUE THREAD

**Issue by rhaex** [goauthentik/authentik#2991]
**Describe the bug**
The default values for the environment properties that allow editing certain user fields (name, email, username) no longer work.

**To Reproduce**
1. Run a fresh Authentik 2022.5.2 installation, with the environment variable `AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME=false`
2. Log in as a user (akadmin is fine)
3. Go to the user settings, change the value for name or email, and click save
4. An error is shown: "Not allowed to change username"

**Expected behavior**
As seen in the docs (and in previous versions), the editing of name and email should default to true (https://goauthentik.io/docs/installation/configuration#authentik_default_user_change_name). When you disable username editing with `AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME` it should not affect the defaults of the other 2 variables. It didn't in previous versions (2022.4.3 and earlier)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.5.2
 - Deployment: both Docker and custom k8s

**Additional context**
A temporary workaround is to explicitly set `AUTHENTIK_DEFAULT_USER_CHANGE_EMAIL=true` and `AUTHENTIK_DEFAULT_USER_CHANGE_NAME=true` besides `AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME=false` and then it works as expected.

**Comment by BeryJu** [comment]
Those variables are actually supposed to marked as deprecated, as starting with 22.3, the user settings are now fully configurable using flow stages and prompts. These variables should still work regardless, they are checked in the `default-user-settings-authorization` policy which is automatically created. That policy has not changed either, so I'm confused as to why they behave differently now. Allthough there might have been a logic error in that policy from the beginning

**Comment by BobSilent** [comment]
I also stumbled across the policy `default-user-settings-authorization` because it's not assigned anywhere
is this correct?

![image](https://user-images.githubusercontent.com/13506173/171056771-4f096634-3644-46b3-8216-b7c356822c44.png)

**Comment by rhaex** [comment]
I tested a bit more, and I think I found out that it happens because we do not use the default `default-user-settings-authorization` but a custom copied version. And it seems that in a recent version a change was applied:

`if not request.user.group_attributes().get(` was replaced with `if not request.user.group_attributes(request.http_request).get(`.

However, I did not know these were deprecated so I will follow up on your advice @BeryJu and remove the properties and the default policy and just create a custom policy for it that does exactly what we want.

You may close this ticket if you want as there is a better alternative for it than using the defaults with properties so for us it no longer is an issue, but I would add it to the documentation so people don't make the same mistake.

**Comment by BeryJu** [comment]
Indeed there was https://github.com/goauthentik/authentik/commit/5861d41ad3f41b92153450569d00c15bf00f6706#diff-9efb262d770edfc3d25c0cb4ed54dddb480d5757719188e39b8a6cce0bf764a7 but that previous version should not have been installed anywhere since it was not part of a release (and even if, the migration would not be re-run)

I've also fixed the above issue of the webinterface saying that policy was not bound https://github.com/goauthentik/authentik/commit/b4d528a78980806ccb2ed18c39981fab12547f92

I'll add the deprecation to the docs, even though there are currently no plans to remove those variables and they should continue to work

**Comment by rhaex** [comment]
After attempting to fix it using a custom policy, it still can't get it to work not work.
I tried:

```
prompt_data = request.context.get("prompt_data")
if prompt_data.get("username") != request.user.username:
    ak_message("Not allowed to change username.")
    ak_message(request.user.username)
    return False
return True
```

And it outputs:
_Not allowed to change username.
AnonymousUser._

**Comment by rhaex** [comment]
I added it, where can I find the output for it?

**Comment by BeryJu** [comment]
Yeah exactly it's in the logs, actually do `ak_logger.warning(request.context)`

My assumption is that the policy should use the request pending user instead of `request.user`, since this uses the flow execute API endpoint instead of directly executing the flow.

**Comment by BeryJu** [comment]
hmm, the context should include a "pending_user" entry as set here https://github.com/goauthentik/authentik/blob/master/authentik/flows/api/flows.py#L367

**Comment by rhaex** [comment]
I simplified it for the sake of testing to:
```
ak_logger.warning(request.context.pending_user)
return True
```

And that results in `Object of type City is not JSON serializable`, logs:
```
{"event": "Object of type City is not JSON serializable", "host": "xxx.xxx.xxx.xxx", "level": "warning", "logger": "authentik.policies.process", "pid": 3932, "request_id": "d365efc485b549ccacdbdb70d3de32e0", "timestamp": "2022-05-31T11:06:35.924200"} 
```

**Comment by rhaex** [comment]
That also did not work, however I have been testing a bit more to verify some things.
We make use of a custom user edit flow, with a custom policy and then set that on the tenant.

So what I did now, as policy:
```
if context["prompt_data"]["username"] != request.user.username:
    ak_message("Not allowed to change username.")
    return False

return True
```

And I import the following flow, and set it as the user edit flow for the tenant:
```
{
  "version": 1,
  "entries": [
    {
      "identifiers": {
        "pk": "e3cee7db-fd1a-4da9-87be-481dbbf06605",
        "slug": "custom-user-settings-flow"
      },
      "model": "authentik_flows.flow",
      "attrs": {
        "name": "Update your info",
        "title": "-",
        "designation": "stage_configuration",
        "cache_count": 1,
        "policy_engine_mode": "any",
        "compatibility_mode": false,
        "layout": "stacked"
      }
    },
    {
      "identifiers": {
        "pk": "237c651e-5519-4b2d-bc72-6e0a1be660b4"
      },
      "model": "authentik_stages_prompt.prompt",
      "attrs": {
        "field_key": "username",
        "label": "Username",
        "type": "text",
        "required": true,
        "placeholder": "try:\n    return user.username\nexcept:\n    return ''",
        "order": 200,
        "sub_text": "",
        "placeholder_expression": true
      }
    },
    {
      "identifiers": {
        "pk": "d538d2c9-edf0-4ccf-b8b2-91aefd42f17d"
      },
      "model": "authentik_stages_prompt.prompt",
      "attrs": {
        "field_key": "name",
        "label": "Name",
        "type": "text",
        "required": true,
        "placeholder": "try:\n    return user.name\nexcept:\n    return ''",
        "order": 201,
        "sub_text": "",
        "placeholder_expression": true
      }
    },
    {
      "identifiers": {
        "pk": "81b0beea-f036-4716-8a6b-29a65704cde6"
      },
      "model": "authentik_stages_prompt.prompt",
      "attrs": {
        "field_key": "email",
        "label": "Email",
        "type": "email",
        "required": true,
        "placeholder": "try:\n    return user.email\nexcept:\n    return ''",
        "order": 202,
        "sub_text": "",
        "placeholder_expression": true
      }
    },
    {
      "identifiers": {
        "pk": "327097fb-c3ad-442b-bbf1-f348f9c13f3c"
      },
      "model": "authentik_stages_prompt.prompt",
      "attrs": {
        "field_key": "attributes.settings.locale",
        "label": "Locale",
        "type": "ak-locale",
        "required": true,
        "placeholder": "try:\n    return user.attributes.get(\"settings\", {}).get(\"locale\", \"\")\nexcept:\n    return ''",
        "order": 203,
        "sub_text": "",
        "placeholder_expression": true
      }
    },
    {
      "identifiers": {
        "pk": "2256261f-9e74-4170-b6f2-78c6886f8aa6"
      },
      "model": "authentik_policies_expression.expressionpolicy",
      "attrs": {
        "name": "custom-user-settings-authorization",
        "execution_logging": false,
        "meta_model_name": "authentik_policies_expression.expressionpolicy",
        "bound_to": 0,
        "expression": "if context[\"prompt_data\"][\"username\"] != request.user.username:\n    ak_message(\"Not allowed to change username.\")\n    return False\n\nreturn True"
      }
    },
    {
      "identifiers": {
        "pk": "4b06a853-27cb-42f2-8808-d181b3324601",
        "name": "custom-user-settings-write"
      },
      "model": "authentik_stages_user_write.userwritestage",
      "attrs": {
        "meta_model_name": "authentik_stages_user_write.userwritestage",
        "create_users_as_inactive": false,
        "create_users_group": null
      }
    },
    {
      "identifiers": {
        "pk": "4b3fa400-4339-4197-9d6e-71374fc0618b",
        "name": "custom-user-settings"
      },
      "model": "authentik_stages_prompt.promptstage",
      "attrs": {
        "meta_model_name": "authentik_stages_prompt.promptstage",
        "fields": [
          "237c651e-5519-4b2d-bc72-6e0a1be660b4",
          "d538d2c9-edf0-4ccf-b8b2-91aefd42f17d",
          "81b0beea-f036-4716-8a6b-29a65704cde6",
          "327097fb-c3ad-442b-bbf1-f348f9c13f3c"
        ],
        "validation_policies": [
          "2256261f-9e74-4170-b6f2-78c6886f8aa6"
        ]
      }
    },
    {
      "identifiers": {
        "pk": "23afb3d9-4787-44a9-a2d8-dc6a9d26ec88",
        "target": "e3cee7db-fd1a-4da9-87be-481dbbf06605",
        "stage": "4b3fa400-4339-4197-9d6e-71374fc0618b",
        "order": 20
      },
      "model": "authentik_flows.flowstagebinding",
      "attrs": {
        "evaluate_on_plan": true,
        "re_evaluate_policies": false,
        "policy_engine_mode": "any",
        "invalid_response_action": "retry"
      }
    },
    {
      "identifiers": {
        "pk": "7d7d68b0-1f53-4645-8bbf-340faa58ab4e",
        "target": "e3cee7db-fd1a-4da9-87be-481dbbf06605",
        "stage": "4b06a853-27cb-42f2-8808-d181b3324601",
        "order": 100
      },
      "model": "authentik_flows.flowstagebinding",
      "attrs": {
        "evaluate_on_plan": true,
        "re_evaluate_policies": false,
        "policy_engine_mode": "any",
        "invalid_response_action": "retry"
      }
    }
  ]
}
```
And then after a restart and a fresh login it works once. Then the next time it will fail even though you did not edit the username. Sometimes CTRL + F5 works, logging out and logging back in always makes it work the next time.

So it seems something is being (incorrectly) cached or not being set each attempt?

**Comment by gueldenstone** [comment]
Would this also cause the `request.user.username` to show `AnonymousUser`? I'm seeing this, when trying to check for uniqueness of emails with 
```python
other_user = ak_user_by(email=context["prompt_data"]["email"])
user = request.user
if (other_user != None and other_user.username != user.username):
    ak_message("Email is already in use by {}. You are: {}".format(other_user.username, user.username))
    return False
return True
```
Output: `"Email is already in use by $CORRECT_USERNAME. You are: AnonymousUser".

**Comment by BeryJu** [comment]
Should be fixed by 2022.6.1, feel free to re open if that's not the case
