### ISSUE TITLE
Proxy env var AUTHENTIK_HOST_BROWSER is not working as expected after upgrading from 2022.11.3 to 2023.2.2

### ISSUE THREAD

**Issue by r-binder** [goauthentik/authentik#4715]
**Describe the bug**
I use authentik and it's proxy provider forward auth with traefik. I set `AUTHENTIK_HOST` to  `http://server:9000` and not to the public domain, so the authentik proxy container can serve authentik server directly.  I set `AUTHENTIK_HOST_BROWSER` to the public domain of my authentik. After upgrading from 2022.11.3 to 2023.2.2 i got a HTTP 400 from the proxy container.  In the logs i found: `oidc: id token issued by a different provider, expected \"http://server:9000/application/o/myproxy-reserve-proxy/\" got \"https://identity.myhost/application/o/myproxy-reserve-proxy/`

When switching `AUTHENTIK_HOST ` env var to the public authentik domain, the proxy works as expected.

**To Reproduce**
1. Create a domain level proxy provider with traefik
2. Set AUTHENTIK_HOST_BROWSER to the public authentik domain and AUTHENTIK_HOST to the internal docker domain (ex. `http://server:9000` )

**Logs**
Docker logs of proxy:
```
{"event":"Loaded config from environment","level":"debug","timestamp":"2023-02-18T16:32:13Z"}
{"event":"not enabling debug server, set `AUTHENTIK_DEBUG` to `true` to enable it.","level":"info","logger":"authentik.go_debugger","timestamp":"2023-02-18T16:32:13Z"}
{"event":"Starting Metrics server","level":"info","listen":"0.0.0.0:9300","logger":"authentik.outpost.metrics","timestamp":"2023-02-18T16:32:13Z"}
{"event":"Starting HTTP server","level":"info","listen":"0.0.0.0:9000","logger":"authentik.outpost.proxyv2","timestamp":"2023-02-18T16:32:13Z"}
{"event":"Starting HTTPS server","level":"info","listen":"0.0.0.0:9443","logger":"authentik.outpost.proxyv2","timestamp":"2023-02-18T16:32:13Z"}
{"event":"Starting authentik outpost","hash":"tagged","level":"info","logger":"authentik.outpost","timestamp":"2023-02-18T16:32:13Z","version":"2023.2.2"}
{"event":"/outpost.goauthentik.io/auth/traefik","host":"myhost","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"myproxy reverse proxy - auth proxy","remote":"172.19.0.2:39768","runtime":"0.588","scheme":"http","size":362,"status":302,"timestamp":"2023-02-18T16:32:57Z","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"}
{"event":"/outpost.goauthentik.io/auth/traefik","host":"myhost","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"myproxy reverse proxy - auth proxy","remote":"172.19.0.2:39768","runtime":"0.205","scheme":"http","size":362,"status":302,"timestamp":"2023-02-18T16:33:20Z","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"}
{"error":"oidc: id token issued by a different provider, expected \"http://server:9000/application/o/myproxy-reserve-proxy/\" got \"https://identity.myhost/application/o/myproxy-reserve-proxy/\"","event":"failed to redeem code","level":"warning","logger":"authentik.outpost.proxyv2.application","name":"myproxy reverse proxy - auth proxy","timestamp":"2023-02-18T16:33:21Z"}
{"event":"/outpost.goauthentik.io/callback?X-authentik-auth-callback=true&code=a733b8652c3e4e818734a62c17d7c0b5&state=Yxz7gI3hPOG0BVoyV5Js-0lixEozhTFWBp4mr-5nf-0","host":"auth-proxy.myhost","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"myproxy reverse proxy - auth proxy","remote":"172.19.0.2:44804","runtime":"69.593","scheme":"http","size":0,"status":400,"timestamp":"2023-02-18T16:33:21Z","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.2.2
 - Deployment: docker-compose

**Comment by sevmonster** [comment]
Related to #4688?

**Comment by telsch** [comment]
If i update the Outpost configuration and set `authentik_host_browser` variable it's working again. But if click on `View Deployment Info` the `AUTHENTIK_HOST_BROWSER` variable still the same as `AUTHENTIK_HOST`.

**Comment by BeryJu** [comment]
this should be fixed with 2023.3, feel free to re-open if that's not the case

**Comment by CuteThun** [comment]
Same issue with LDAP Outpost. if I set `authentik_host_insecure: true`.
Docker outpost logs:
```
goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0005570a0, 0x0, {0xc0000b2af8, 0x14})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x4d6
github.com/sirupsen/logrus.(*Entry).Log(0xc0005570a0, 0x0, {0xc0005bfe50?, 0xfc7060?, 0xc00047e600?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:342
main.main()
        /go/src/goauthentik.io/cmd/ldap/main.go:73 +0x585
{"event":"Loaded config from environment","level":"debug","timestamp":"2023-03-16T06:56:16Z"}
{"event":"not enabling debug server, set `AUTHENTIK_DEBUG` to `true` to enable it.","level":"info","logger":"authentik.go_debugger","timestamp":"2023-03-16T06:56:16Z"}
{"error":"500 Internal Server Error","event":"Failed to run server","level":"panic","timestamp":"2023-03-16T06:56:17Z"}
{"event":"finished shutdown","level":"info","logger":"authentik.outpost.ak-api-controller","timestamp":"2023-03-16T06:56:17Z"}
panic: (*logrus.Entry) 0xc000118460
```

**Comment by elythh** [comment]
Running 2023.4 and configuring the embedded outpost `authentik_host_browser` to a different url than `authentik_host` does not work.

**Comment by ArjonBu** [comment]
This is not working for me on 2023.8.1 release.

**Comment by Ornias1993** [comment]
@BeryJu The fact this is closed and STILL broken, is, quite frankly, not acceptable.

**Comment by Ornias1993** [comment]
even a year later, I might add.

**Comment by andymarden** [comment]
I am trying to run authentik at two URLs: the first one was let's say auth.example.org and I have the embedded outpost set to that of course.

Now I want to be able to have the same authentik at auth.example.com.

Nginx takes care of the direct of both these to the same server - so all good

But I believe I need a 2nd outpost for that different host.

I create a new one and set the host to https://auth.example.com then I get the deployment info screen. It shows https://auth.example.org as both the host and the url.

If I set authentik_host_browser to https://auth.example.com then a blank error pops up and I can't progress.

How is this not a bug and how is it not fixed by now?

I guess I need to deploy a 2nd instance of authentik which is a right pain.

**Comment by tuxmainy** [comment]
I guess a closed issue won't get enough attention. Have a look at [#9622](https://github.com/goauthentik/authentik/issues/9622). Maybe we should push the new issue?
