### ISSUE TITLE
Can't make OAuth2 work with Wiki JS

### ISSUE THREAD

**Issue by EHRETic** [goauthentik/authentik#7974]
**Describe the bug**
Despite I was able to configure a working Portainer Oauth, I can't get WikiJS to work with same user

**To Reproduce**
1. Configure WikiJS Oauth2 generic OpenID
2. Try to login
3. Wiki site redirects me to auth
4. Auth works bur access to WikiJS fails

**Expected behavior**

**Screenshots**
Configuration of WikiJS (wich is not a one to one match of the documentation (some extra fields
![image](https://github.com/goauthentik/authentik/assets/28634810/8b8fb29d-ff49-4590-88d1-8c19b9eb66f8)

Error
![image](https://github.com/goauthentik/authentik/assets/28634810/c730b312-d9b2-4f4b-a5d2-b7f556dbdc05)

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.11/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/ak-root/venv/lib/python3.11/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/ak-root/venv/lib/python3.11/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/ak-root/venv/lib/python3.11/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/ak-root/venv/lib/python3.11/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/rest_framework/authentication.py", line 130, in authenticate
    self.enforce_csrf(request)
  File "/ak-root/venv/lib/python3.11/site-packages/rest_framework/authentication.py", line 148, in enforce_csrf
    raise exceptions.PermissionDenied('CSRF Failed: %s' % reason)
rest_framework.exceptions.PermissionDenied: CSRF Failed: Origin checking failed - https://auth-test.mydomain.ext does not match any trusted origins.
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2023.10.5
- Docker container with macvlan IP adresses

**Additional context**
- I use LetsEncrypt certificates for both instances (authentik & wikijs), both are behind an NGINX reverse proxy
- A Portainer instance works fine
- I use Incognito mode for testing
- all my users are AD based (but I don't think it matters)

**Comment by PythonCoderAS** [comment]
You might need to set the redirect URL first.

**Comment by EHRETic** [comment]
> You might need to set the redirect URL first.

Hi,

I might be mistaken, but I put the URL mentioned by WikiJS Oauth configuration there:
(the one ou see at the bottom of the configuration in my previous screenshot, in the Configuration Reference area)

![image](https://github.com/goauthentik/authentik/assets/28634810/2c9b5e52-c0f8-4955-8f2c-ba5a2db777fd)

Is that correct?

PS: Might be a WikiJS issue too, I'll try to get some logs from there.

**Comment by PythonCoderAS** [comment]
I've retired my wikijs installation but these are the values I pulled from Postgresql:

```json
{
  "clientId": "myclientid",
  "clientSecret": "myclientsecret",
  "authorizationURL": "https://sso.mydomain.com/application/o/authorize/",
  "tokenURL": "https://sso.mydomain.com/application/o/token/",
  "userInfoURL": "https://sso.mydomain.com/application/o/userinfo/",
  "skipUserProfile": false,
  "issuer": "https://sso.mydomain.com/application/o/wikijs/",
  "emailClaim": "email",
  "displayNameClaim": "displayName",
  "mapGroups": false,
  "groupsClaim": "groups",
  "logoutURL": "https://sso.mydomain.com/application/o/wikijs/end-session/",
  "acrValues": ""
}
```

**Comment by PythonCoderAS** [comment]
By chance, is your wikijs domain and Authentik domain different?

**Comment by PythonCoderAS** [comment]
I did some investigating and found this: https://stackoverflow.com/a/71482883/12248328

In your reverse proxy for Authentik and Wikijs, do you have this line (or the equivalent):

```
        proxy_set_header X-Forwarded-Proto $scheme;
```

If you don't, adding this line should fix the error.

**Comment by EHRETic** [comment]
> proxy_set_header X-Forwarded-Proto $scheme;

YYYEEEEESSSSS, it works! 👍

Thank you so much!!! 😊

If by any chance, you have some good "NGINX for newbies" website to recommend, that would allow me to understand what this line really does and why it is necessary in that case. I still can't get the full picture of all the options available in NGINX.

**Comment by EHRETic** [comment]
> proxy_set_header X-Forwarded-Proto $scheme;

YYYEEEEESSSSS, it works! 👍

Thank you so much!!! 😊

If by any chance, you have some good "NGINX for newbies" website to recommend, that would allow me to understand what this line really does and why it is necessary in that case. I still can't get the full picture of all the options available in NGINX.
